import { defineConfig } from 'cspell'

export default defineConfig({
  overrides: [
    {
      filename: 'content/**',
      enabled: false,
    },
    {
      filename: 'content/**/en.mdx',
      language: 'en',
      enabled: true,
    },
    {
      words: [
        'амэку',
        'бенчмарки',
        'ванпанчмен',
        'ватсап',
        'годзилла',
        'дандадан',
        'джованни',
        'дороро',
        'дорохедоро',
        'евангелион',
        'емайл',
        'кайдзю',
        'кинокружка',
        'контрибьюторов',
        'линкед',
        'лоферах',
        'мастодон',
        'мононоке',
        'ньюс',
        'опенсорс',
        'пайплайн',
        'психо',
        'психопаспорт',
        'реддит',
        'серокрылых',
        'сонни',
        'судзумии',
        'такао',
        'такопи',
        'таймлайн',
        'тоторо',
        'фрирен',
        'фронтенд',
        'харухи',
        'хаула',
        'шаймухаметов',
        'этти',
      ],
      filename: [
        '**/content/**/ru.mdx',
        '**/locales/ru.ts',
        '**/public/manifest-ru.json',
      ],
      language: 'en,ru',
    },
  ],
  words: [
    'alya',
    'ameku',
    'astro',
    'astrojs',
    'azat',
    'bluesky',
    'bocchi',
    'browserslistrc',
    'bsky',
    'butareba',
    'dededededestruction',
    'dorohedoro',
    'dororo',
    'ecchi',
    'edgerunners',
    'eizouken',
    'elfen',
    'evangelion',
    'frieren',
    'fullmetal',
    'gruvbox',
    'haruhi',
    'hastscript',
    'infobox',
    'kaiju',
    'kaisen',
    'katex',
    'kiki',
    'kindspells',
    'lightningcss',
    'maison',
    'mdast',
    'mecha',
    'mononoke',
    'mugen',
    'mushi',
    'mushoku',
    'neverland',
    'nuxt',
    'onimai',
    'oshi',
    'parasyte',
    'playform',
    'poppanator',
    'preact',
    'rehype',
    'reze',
    'shaimukhametov',
    'shiki',
    'sonarjs',
    'squoosh',
    'suzumiya',
    'swordsmith',
    'takopi',
    'tekkonkinkreet',
    'tensei',
    'totoro',
    'typograf',
    'umami',
    'uzumaki',
    'ycombinator',
  ],
  ignorePaths: [
    '.github',
    'cspell.config.ts',
    'license.md',
    'pnpm-lock.yaml',
    'styles',
    'themes',
    'tsconfig.json',
  ],
  dictionaries: ['css', 'html', 'node', 'npm', 'typescript'],
  import: ['@cspell/dict-ru_ru/cspell-ext.json'],
  useGitignore: true,
  language: 'en',
})
